---
- hosts: load-balancers
  gather_facts: false
  vars:
    jinja_src_location: "{{ haproxy.jinja_template.src_location }}"
    remote_haproxy_config: "{{ haproxy.jinja_template.dest_location }}"
  tasks:    
     - name: Install HaProxy
       ansible.builtin.apt:
         name: haproxy
         state: present
    
     - name: Apply HaProxy Configuration From Source
       ansible.builtin.template:
         src: "{{ jinja_src_location }}"
         dest: "{{ remote_haproxy_config }}"
      
     - name: Reload haproxy
       ansible.builtin.service:
         name: haproxy
         state: restarted