---
mongodb:
  server:
    port: 27017
    ssl: false
    ssl_cert_reqs: "CERT_NONE"
    validate: false
    bindIP: 0.0.0.0
    config_path: /etc/mongod.conf
    repository_path: /etc/apt/trusted.gpg.d/mongodb-6.gpg
  database:
    username:
    password:
    name: graylog
    roles: 
      - readWrite
      - dbAdmin
      - userAdmin
  replica_set:
    name: replicaset-01